public with sharing class Constants {
    public static String CLOCKED_IN = 'Clocked In';
    public static String CLOCKED_OUT = 'Clocked Out';
    public static String CLOCKED_IN_ANOTHER = 'Clocked in on another job';
    public static String LICENSE_EXCEEDED_ERROR = 'LICENSE_LIMIT_EXCEEDED';
    public static String REQ_FIELDS_MISSING = 'Required Fields Missing';
    public static String NO_EMAIL_ON_CONTACTS = 'No Email on Contacts';
    public static String FIELD_INTEGRITY = 'Field Integrity';
    public static String DUPLICATE_USERNAME = 'Duplicate Username';
    public static String INVALID_EMAIL = 'INVALID_EMAIL_ADDRESS';
    public static String USER_OBJECT_MISSING = 'Script-thrown exception';
    public static String MSG_LICENSE_EXCEEDED = 'License Not Available For The Selected Profile';
    public static String MSG_REQ_FIELDS_MISSING = 'Required Fields Are Missing On Users! Please Check';
    public static String MSG_FIELD_INTEGRITY = 'Incorrect Data On Fields! Please Review Values & Try Again';
    public static String MSG_NO_EMAIL_ON_CONTACTS = 'Please Review Selected Contact Record, Email Is Missing On Them.';
    public static String MSG_DUPLICATE_USERNAME = 'Duplicate Username Found! Please Modify Firstname,Lastname Or Domain!';
    public static String MSG_INVALID_EMAIL = 'Invalid Email Format Please Review Contact Email!';
    public static String MSG_USER_MISSING = 'You do not have access to creating Users!Please update your profile!';
}