import { createElement } from '@lwc/engine-dom';
import Cmp_audioRecorder from 'c/cmp_audioRecorder';

describe('c-cmp-audio-recorder', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-cmp-audio-recorder', {
            is: Cmp_audioRecorder
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});